### PR TITLE
Add quarkus-sa-token to extension catalog

### PR DESCRIPTION
**Pull request by zhfeng**
It should fix https://github.com/quarkiverse/quarkus-sa-token/issues/63

### CODE REVIEW

**Comment by gastaldi** [comment]
@zhfeng can you rename them using the `quarkiverse-sa-token-*` pattern (with a `-`) to match the repository name? 

Also I find it weird that the artifactId used in your releases are missing this too.

**Comment by zhfeng** [comment]
@gastaldi I think it uses `io.quarkiverse.satoken` as groupId. Is there any issue if the groupId is not match with the repository name?

@naah69 can you confirm the groupId is correct?

**Comment by gastaldi** [comment]
> @gastaldi I think it uses `io.quarkiverse.satoken` as groupId. Is there any issue if the groupId is not match with the repository name?

@zhfeng no, no issue at all, just curious why the `-` is missing since the project also has a `-`: https://sa-token.dev33.cn/

**Comment by zhfeng** [comment]
I have no idea. Maybe @naah69 can answer it.

**Comment by naah69** [comment]
> > @gastaldi I think it uses `io.quarkiverse.satoken` as groupId. Is there any issue if the groupId is not match with the repository name?
> 
> @zhfeng no, no issue at all, just curious why the `-` is missing since the project also has a `-`: https://sa-token.dev33.cn/ https://github.com/dromara/Sa-Token

i found that `satoken` in package name.
so i set it without `-` when i created project.
image
****

i will change it to match pattern.

**Review by gastaldi — APPROVED** [review]

**Pull request merged**
