### PR TITLE
Extension relocation : quarkus-messaging-nats-jetstream

### PR DESCRIPTION
**Pull request by ozangunalp**
Created a new entry to the catalog for `quarkus-messaging-nats-jetstream` and disabled the old one: `quarkus-reactive-messsaging-nats-jetstream`

### CODE REVIEW

**Comment by ozangunalp** [comment]
@gastaldi I've proposed this change to handle the failing catalog update job https://github.com/quarkusio/quarkus-extension-catalog/actions/runs/10682006853/job/29606854304. 
I don't know if there is a better way to handle relocations.

It was first reported here : https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/issues/182

**Comment by gastaldi** [comment]
@ozangunalp Should `quarkus-reactive-messsaging-nats-jetstream` be removed from the registry?

**Comment by ozangunalp** [comment]
No, I don't think so. previous versions are still valid.

**Comment by holly-cummins** [comment]
For what it's worth, I've confirmed https://quarkus.io/extensions/io.quarkiverse.reactivemessaging.nats-jetstream/quarkus-reactive-messsaging-nats-jetstream/ is doing the right thing:

image

(There's a weird thing where the search on the front page doesn't find the extension, but I think that's unrelated to the relocation, and just a mystery bug. I'll investigate.)

**Pull request merged**
