### PR TITLE
Create vaadin.yaml

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes https://github.com/vaadin/quarkus/issues/105

### CODE REVIEW

**Comment by mcollovati** [comment]
Thank you very much @gastaldi

**Comment by mcollovati** [comment]
@gastaldi One additional question: in our [starter project](https://github.com/vaadin/base-starter-flow-quarkus) we usually do not depend directly on the extension runtime artifact, but on [vaadin-quarkus-extension](https://central.sonatype.com/artifact/com.vaadin/vaadin-quarkus-extension/24.0.5) that is a Vaadin platform artifact that imports the Vaadin extension, the jandex index and the collection of UI components.

For the Quarkus catalog, is it mandatory to point to the runtime artifact or can we reference `vaadin-quarkus-extension`?

**Comment by gastaldi** [comment]
@mcollovati the `vaadin-quarkus-extension` is not a Quarkus extension, therefore it can't be included in the registry. The artifacts listed in this catalog all contain a JAR with a `META-INF/quarkus-extension.yaml` to be considered a valid extension. If you could include that YAML in the distribution maybe we could replace the existing artifact with this one

**Comment by mcollovati** [comment]
I'll discuss this with the team. Thanks for the information.

**Comment by mcollovati** [comment]
@gastaldi I did some test locally adding the `quarkus-extension.yaml` to `vaadin-quarkus-extension` jar and using this dependency with the `create` goal of `quarkus-maven-plugin` and it worked fine.
So, once we will have the new platform artifacts released, with the added file, I'll create a new PR to update `info.yaml` 

/cc @manolo @mstahv

**Pull request merged**
