### PR TITLE
Create quarkus-bom.yaml

### PR DESCRIPTION
**Pull request by gastaldi**
This will register quarkus-bom along with its members in registry.quarkus.io. 

See https://github.com/quarkusio/registry.quarkus.io/commit/a847c9a9b91e0453b121fe48178d99174c6eb5fd

### CODE REVIEW

**Comment by aloubyansky** [comment]
We don't want `io.quarkus:quarkus-bom` in the registry. We want `io.quarkus.platform:quarkus-bom`.

**Comment by gastaldi** [comment]
@aloubyansky  This is what this PR will enable:

```json
{
  "platforms": [
    {
      "platform-key": "io.quarkus.platform",
      "name": "Member specific BOMs"
    },
    {
      "platform-key": "io.quarkus",
      "name": "Quarkus BOM",
      "streams": [
        {
          "id": "2.0",
          "releases": [
            {
              "version": "2.0.0.Final",
              "member-boms": [
                "io.quarkus.platform:quarkus-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-cassandra-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-hazelcast-client-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-google-cloud-services-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-optaplanner-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-qpid-jms-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-blaze-persistence-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-debezium-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-camel-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final",
                "io.quarkus.platform:quarkus-kogito-bom-quarkus-platform-descriptor:2.0.0.Final:json:2.0.0.Final"
              ],
              "quarkus-core-version": "2.0.0.Final"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by aloubyansky** [comment]
It has to be under `io.quarkus.platform` and if you could change it to the BOMs with `PlatformArtifacts.ensureBomArtifact(coords) that'd be a plus.

**Comment by aloubyansky** [comment]
There could still be the 1.13.7.Final universe bom under `io.quarkus` though.

**Comment by gastaldi** [comment]
@aloubyansky okay, changed it and it's now: 

```json
{
  "platforms": [
    {
      "platform-key": "io.quarkus.platform",
      "name": "Member specific BOMs",
      "streams": [
        {
          "id": "2.0",
          "releases": [
            {
              "version": "2.0.0.Final",
              "member-boms": [
                "io.quarkus.platform:quarkus-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-cassandra-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-hazelcast-client::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-google-cloud-services-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-optaplanner-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-qpid-jms-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-blaze-persistence-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-debezium-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-camel-bom::pom:2.0.0.Final",
                "io.quarkus.platform:quarkus-kogito-bom::pom:2.0.0.Final"
              ],
              "quarkus-core-version": "2.0.0.Final"
            }
          ]
        }
      ]
    },
    {
      "platform-key": "io.quarkus",
      "name": "Quarkus BOM"
    }
  ]
}
```

**Comment by aloubyansky** [comment]
That looks ok. I guess the name could be changed to something more meaningful once the dev tools will actually start displaying it.

**Comment by aloubyansky** [comment]
How difficult would it be to add the 1.13.7.Final platform?

**Comment by gastaldi** [comment]
> How difficult would it be to add the 1.13.7.Final platform?

1.13.7 is already in the production database (see https://registry.quarkus.io/client/platforms). That output was from my local empty database after applying this change

> That looks ok. I guess the name could be changed to something more meaningful once the dev tools will actually start displaying it.

Can you submit a PR to https://github.com/quarkusio/registry.quarkus.io/blob/main/src/main/resources/db/migration/V3__Add_platforms.sql? I'll make sure to have that applied in the production DB

**Review by aloubyansky — APPROVED** [review]

**Pull request merged**
