### PR TITLE
Add Lunatech as a named sponser

### PR DESCRIPTION
**Pull request by wjglerum**
cc @FroMage 🎉

### CODE REVIEW

**Comment by holly-cummins** [comment]
Hurray, that's live! 
For example, https://quarkus.io/extensions/io.quarkiverse.wiremock/quarkus-wiremock/?tab=community

image

**Comment by wjglerum** [comment]
> Hurray, that's live! For example, 

Awesome, thanks! 

Just out of curiosity, how does it guess this? The docs are pretty brief on this 😄
> but if there isn't one there, we try to guess.

**Comment by wjglerum** [comment]
Ah I think I found something here https://github.com/quarkusio/extensions/blob/main/plugins/github-enricher/sponsorFinder.js

**Comment by holly-cummins** [comment]
That's the one - we use the company information in people's GitHub profiles, and do a bit of normalisation.

**Pull request merged**
